export interface SiteLinks {
  youtube: string;
  instagramRasa: string;
  instagramPersonal: string;
  email: string;
  emailLabel: string;
  phone: string;
  phoneLabel: string;
  cv: string;
}

export interface SiteBrand {
  rasaLogo: string;
  artsyLogo: string;
  youtubeIcon: string;
  instagramIcon: string;
  aboutPortrait: string;
}

export interface HomeNavItem {
  label: string;
  path: string;
  image: string;
}

export interface SiteContent {
  siteName: string;
  tagline: string;
  editor: string;
  links: SiteLinks;
  brand: SiteBrand;
  home: {
    heroLead: string;
    introParagraphs: string[];
    /** Homepage photo strip — generated by scripts/optimize-gallery.mjs */
    gallery: string[];
    nav: HomeNavItem[];
    partnershipLinkLabel: string;
    partnershipHeroLabel: string;
    partnershipLinkPath: string;
  };
}

export interface PartnershipOffering {
  title: string;
  text: string;
}

export interface PartnershipContent {
  title: string;
  intro: string[];
  sponsor: {
    eyebrow: string;
    title: string;
    paragraphs: string[];
    bullets: string[];
    closing: string[];
    ctaTitle: string;
    ctaText: string;
  };
  collaborations: {
    eyebrow: string;
    title: string;
    paragraphs: string[];
    offerings: PartnershipOffering[];
    closing: string[];
    ctaTitle: string;
    ctaText: string;
  };
  editorial: {
    title: string;
    paragraphs: string[];
  };
  contact: {
    title: string;
    paragraphs: string[];
    enquiryIntro: string;
    enquiryBullets: string[];
    closing: string;
  };
}

export interface MagazineIssue {
  id: string;
  title: string;
  volume: number;
  month: string;
  year: number;
  cover: string;
  /** Local PDF under public/ — synced from Google Drive during deploy */
  pdfUrl?: string;
  /** Pre-rendered flip-book page images under public/ */
  pagesBase?: string;
  pageCount?: number;
  pageExt?: string;
  /** Public Google Drive link for full-quality download */
  driveUrl: string;
  published: boolean;
}

export interface VideoSeries {
  id: string;
  title: string;
  description: string;
  playlistUrl: string;
  embedUrl: string;
}

export interface VideosIndex {
  intro: string;
  series: VideoSeries[];
}
